# Generated by Django 4.2.7 on 2026-01-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signup_device', models.CharField(blank=True, max_length=255)),
                ('signup_browser', models.CharField(blank=True, max_length=255)),
                ('signup_referrer', models.URLField(blank=True)),
                ('signup_utm_source', models.CharField(blank=True, max_length=255)),
                ('signup_utm_medium', models.CharField(blank=True, max_length=255)),
                ('signup_utm_campaign', models.CharField(blank=True, max_length=255)),
                ('is_first_signup', models.BooleanField(default=True)),
                ('signup_completed', models.BooleanField(default=True)),
                ('signup_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign Up Data',
                'verbose_name_plural': 'Sign Up Data',
                'db_table': 'signup_data',
            },
        ),
    ]
