# Generated by Django 4.2.7 on 2026-01-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_signupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_browser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_referrer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Normal User'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
        migrations.DeleteModel(
            name='SignUpData',
        ),
    ]
