# Generated by Django 4.2.7 on 2026-01-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_first_signup_user_signup_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientprofile',
            name='doctor_contact',
        ),
        migrations.RemoveField(
            model_name='recipientprofile',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='recipientprofile',
            name='eligibility_certificate',
        ),
        migrations.RemoveField(
            model_name='recipientprofile',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='recipientprofile',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='fitness_certificate',
            field=models.FileField(blank=True, null=True, upload_to='fitness_certificates/'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='lab_reports',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='medical_fitness_status',
            field=models.CharField(choices=[('fit', 'Fit'), ('not_fit', 'Not Fit')], default='fit', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('fit', 'Fit'), ('not_fit', 'Not Fit'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('fit', 'Fit'), ('not_fit', 'Not Fit'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
