# Generated by Django 4.2.7 on 2026-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_recipientprofile_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
