# Generated by Django 4.2.7 on 2026-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipientprofile_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
