# Generated by Django 4.2.7 on 2026-01-23 14:41

from django.db import migrations
import random
import string
from datetime import datetime


def generate_registration_id(user_type, existing_ids):
    """Generate unique registration ID"""
    date_str = datetime.now().strftime('%Y%m%d')
    random_str = ''.join(random.choices(string.digits, k=4))
    
    if user_type == 'donor':
        registration_id = f"LCR-DON-{date_str}-{random_str}"
    else:
        registration_id = f"LCR-REC-{date_str}-{random_str}"
    
    # Ensure uniqueness
    while registration_id in existing_ids:
        random_str = ''.join(random.choices(string.digits, k=4))
        if user_type == 'donor':
            registration_id = f"LCR-DON-{date_str}-{random_str}"
        else:
            registration_id = f"LCR-REC-{date_str}-{random_str}"
    
    return registration_id


def populate_registration_ids(apps, schema_editor):
    """Populate registration IDs for existing records"""
    DonorProfile = apps.get_model('main', 'DonorProfile')
    RecipientProfile = apps.get_model('main', 'RecipientProfile')
    
    # Get existing registration IDs
    existing_ids = set()
    existing_ids.update(DonorProfile.objects.exclude(registration_id='').values_list('registration_id', flat=True))
    existing_ids.update(RecipientProfile.objects.exclude(registration_id='').values_list('registration_id', flat=True))
    
    # Update donor profiles
    for donor in DonorProfile.objects.filter(registration_id=''):
        donor.registration_id = generate_registration_id('donor', existing_ids)
        donor.save()
        existing_ids.add(donor.registration_id)
    
    # Update recipient profiles
    for recipient in RecipientProfile.objects.filter(registration_id=''):
        recipient.registration_id = generate_registration_id('recipient', existing_ids)
        recipient.save()
        existing_ids.add(recipient.registration_id)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_donorprofile_registration_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_registration_ids),
    ]
