# Generated by Django 4.2.7 on 2026-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20260123_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='registration_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='registration_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
