# Generated by Django 4.2.7 on 2026-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20260123_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='taking_medications',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
