# Generated by Django 4.2.7 on 2026-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_donorprofile_taking_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='lab_reports',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
