# Generated by Django 4.2.7 on 2026-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recipientprofile_doctor_name_recipientprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='hospital_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
