# Generated by Django 4.2.7 on 2026-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20260126_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='doctor_name',
            field=models.CharField(blank=True, help_text="Doctor's full name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='hospital_address',
            field=models.TextField(blank=True, help_text='Hospital address', null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Hospital name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
