# Generated by Django 4.2.7 on 2026-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_recipientprofile_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
