# Generated by Django 4.2.7 on 2026-03-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_donorprofile_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='donation_after_death',
        ),
    ]
