# Generated by Django 4.2.7 on 2026-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_donorprofile_donation_after_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='donation_after_death',
            field=models.BooleanField(default=True),
        ),
    ]
